a = float(input("Enter a number: "))
b = float(input("Enter another number: "))
print("Addition:\t\t" + str(a) + " + " + str(b) + " = " + str(a + b))
print("Subtraction:\t\t" + str(a) + " - " + str(b) + " = " + str(a - b))
print("Multiplication:\t\t" + str(a) + " * " + str(b) + " = " + str(a * b))
print("Division:\t\t" + str(a) + " / " + str(b) + " = " + str(a / b))
