writingFile = open("output.txt", "w")
writingFile.write(input("Enter text to write to the file: ") + "\n")
writingFile.close()
print("Data successfully written to output.txt.\n")
appendingFile = open("output.txt", "a")
appendingFile.writelines(input("Enter additional text to append:") + "\n")
appendingFile.close()
print("Data successfully appended.\n\nFinal content of output.txt:")
readingFile = open("output.txt", "r")
print(readingFile.read())
